### ISSUE TITLE
There are some layout issues in this theme

### ISSUE THREAD

**Issue by olivertzeng** [nicefaa6waa/genshin-sddm-theme#1]
https://asciinema.org/a/KkcHzhXa47lheEu9JnVUC6Abf
![Screenshot_20231205_190230](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/86348833/de8b8f61-0d10-4ee3-a6b9-dd22f587bfd1)

**Comment by nicefaa6waa** [comment]
It may be an issue related to your resolution or useless variables in the code since I've used anothed theme as my main code.I've tried this theme on my 3 different computers including Debian and Arch.So far had no issues in any of them.I'll try to take a deeper look to it as soon as possible.Have a great day!

**Comment by olivertzeng** [comment]
Thanks for your kind reply!
I'm using sddm with the `sddm-git` AUR package and I'll provide my pfetch.

**Comment by olivertzeng** [comment]
https://asciinema.org/a/625312

**Comment by nicefaa6waa** [comment]
- [x] Use % instead of pixels for margins and borders
- [x] Optimize video players to be scalable for different resolutions
- [ ] Final bug checks and fixes
