### ISSUE TITLE
Invalid theme package

### ISSUE THREAD

**Issue by FujaTyping** [nicefaa6waa/genshin-sddm-theme#26]
![image](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/86290693/87ce9681-61a0-477e-8529-7092030d377d)
![image](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/86290693/a530e2a6-c528-4b0b-aac0-7b9e0d5b7fb8)
I download a `genshin.tar.xz` file from [store.kde.org](https://store.kde.org/p/2111715) and install from file in setting , I got this error
> System : Archlinux (Endeavouros)
> KDE : 6.0.1
> Qt Version : 6.6.2
> Session : X11

**Comment by nicefaa6waa** [comment]
Okay so here is the issue.First in another issue i mentioned that this teme only works for 1920x1080 resolution.
Adding view for "eDP-1" QRect(0,0 1366x768)
Indicates that you are on another resoltuion.That explains the layout issue
In the second log 
Warning: "A lot of buffers are being dropped."
Indicates that your hardware is not good enough to run the theme or there are some compatibility issues.And lastly about logging in:
QIODevice::write (QLocalSocket): device not open
This issue indicates sddm couldn't start the system.It happens if you are using sddm-greeter.It can't open the system if you are already logged in.It is same for everyone once you make it the default theme and use it as normal it works.There are some another issues with other video codecs after i added Qt6 flag to fix the slow door animation issue.Im always trying to further optimize the theme to fix complatibility issues.Sorry again for the inconvenience and thanks a lot for providing the log files.Currently im in college so i know fixes may be slow sometimes and im again sorry for that.Still im trying my best to fix issues as soon as possible.Thank you for using my sddm theme.Have a good day!

**Comment by nicefaa6waa** [comment]
With the latest update fixed the layout issue and cleared some other things that may cause lagging issues.Layout issue must be mostly fixed but please let me know if you still have any issues.About the KDE Package i don't have KDE myself so i will downlaod it and upload the package to KDE Store asap.Thanks again for your report and helping me to make this theme eevn better!
