### ISSUE TITLE
How to fix it i can't fix it by my self help me please.

### ISSUE THREAD

**Issue by MikihinaSann** [nicefaa6waa/genshin-sddm-theme#44]
The current theme cannot be loaded due to the errors below, please select another theme.

file:///usr/share/sddm/themes/genshin-sddm-theme//Main.qml:5:1: plugin cannot br loaded for module "QtQuick.Controls": Cannot protect module QtQuick.Controls 2 as it was never registered

**Comment by nicefaa6waa** [comment]
Check #34

**Comment by nicefaa6waa** [comment]
So sorry for the late reply i've been working on a big update! I just wanted to let you know that your issue seems to be the same as the one mentioned in #34. If you follow the steps there, it should help you fix things up! But if you're still having any trouble after that, feel free to reach out to me anytime, and I’ll be happy to help. 

Have a great day and thank you for using genshin-sddm-theme <3

Take care,
churchy 💜

**Comment by nicefaa6waa** [comment]
Closed as no response.Please re-open this issue if your problem still exists or if you have any more questions.Have a freat day 🙏🏻
